language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"

install:
  - pip install $DJANGO
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls
